server:
    port: 80
    tomcat:
      uri-encoding: UTF-8
spring:
  profiles:
    active: test
  application:
    name: admin
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  #模板引擎配置
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: rc
      charset: UTF-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
#  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.admin.module.entity
  global-config:
    db-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 ignore:"忽略判断",not_null:"非 NULL 判断"),not_empty:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置 （Y：正常；N：删除；A：审核(手动设定)；）
      #logic-delete-value: 'N'
      #logic-not-delete-value: 'Y'
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


